/**
 * SitePanel v4
 *
 * Читает/пишет:
 *   src/shared/data/seo.ts   — глобальный SEO конфиг
 *   public/robots.txt        — индексирование
 *   public/llm.txt           — AI боты
 *
 * ВАЖНО: googleVerify/yandexVerify убраны — проект публичный статический,
 * ключи верификации НЕ должны попадать в исходники.
 */

import React, { useState, useEffect, useCallback, useContext, useRef } from 'react';
import { bridge } from '../useDevBridge';
import { toast } from '../components/Toast';
import { ThemeTokensContext } from '../DevPanel';
import type { TTokens } from '../DevPanel';
import {
  Globe, Search, Bot, RefreshCw, Loader2,
  ChevronDown, ChevronRight, Check,
} from 'lucide-react';

// ─── Types ────────────────────────────────────────────────────────────────────

interface SiteConfig {
  // Основное
  siteTitle:       string;
  siteDescription: string;
  siteUrl:         string;
  siteLang:        string;
  siteAuthor:      string;
  keywords:        string;
  // SEO
  metaRobots:      string;
  ogImage:         string;
  ogType:          string;
  ogLocale:        string;
  twitterCard:     string;
  twitterSite:     string;
  // robots.txt
  robotsAllowAll:      boolean;
  robotsDisallowPaths: string;
  // llm.txt
  llmEnabled:      boolean;
  llmUsagePolicy:  string;
  llmContact:      string;
  llmDescription:  string;
}

const DEFAULTS: SiteConfig = {
  siteTitle:           'Hub — Opensophy',
  siteDescription:     'Hub проекта Opensophy — центр знаний по ИИ и кибербезопасности.',
  siteUrl:             'https://hub.opensophy.com',
  siteLang:            'ru',
  siteAuthor:          'Opensophy',
  keywords:            'opensophy, hub, документация, AI, кибербезопасность',
  metaRobots:          'index, follow',
  ogImage:             '/og-image.png',
  ogType:              'website',
  ogLocale:            'ru_RU',
  twitterCard:         'summary_large_image',
  twitterSite:         '',
  robotsAllowAll:      true,
  robotsDisallowPaths: '',
  llmEnabled:          true,
  llmUsagePolicy:      'allowed',
  llmContact:          '',
  llmDescription:      '',
};

const SEO_PATH    = 'src/shared/data/seo.ts';
const ROBOTS_PATH = 'public/robots.txt';
const LLM_PATH    = 'public/llm.txt';

// ─── Serializers ──────────────────────────────────────────────────────────────

function buildSeoTs(cfg: SiteConfig): string {
  return `// Auto-generated by Hub Dev Panel — Вкладка "Сайт"
// Редактировать через Dev Panel, не вручную

export const SEO_CONFIG = {
  siteTitle:       ${JSON.stringify(cfg.siteTitle)},
  siteDescription: ${JSON.stringify(cfg.siteDescription)},
  siteUrl:         ${JSON.stringify(cfg.siteUrl)},
  siteLang:        ${JSON.stringify(cfg.siteLang)},
  siteAuthor:      ${JSON.stringify(cfg.siteAuthor)},
  keywords:        ${JSON.stringify(cfg.keywords)},
  metaRobots:      ${JSON.stringify(cfg.metaRobots)},
  ogImage:         ${JSON.stringify(cfg.ogImage)},
  ogType:          ${JSON.stringify(cfg.ogType)},
  ogLocale:        ${JSON.stringify(cfg.ogLocale)},
  twitterCard:     ${JSON.stringify(cfg.twitterCard)},
  twitterSite:     ${JSON.stringify(cfg.twitterSite)},
} as const;
`;
}

function buildRobotsTxt(cfg: SiteConfig): string {
  const lines: string[] = ['User-agent: *', 'Allow: /'];

  if (!cfg.robotsAllowAll) {
    cfg.robotsDisallowPaths
      .split('\n')
      .map(l => l.trim())
      .filter(Boolean)
      .forEach(p => lines.push(`Disallow: ${p}`));
  }

  const base = cfg.siteUrl.replace(/\/$/, '');
  if (base) {
    lines.push('', `Sitemap: ${base}/sitemap.xml`);
  }

  lines.push('', '# AI crawlers');
  const aiRule = cfg.llmEnabled ? 'Allow: /' : 'Disallow: /';
  ['GPTBot', 'Claude-Web', 'anthropic-ai', 'PerplexityBot', 'Applebot-Extended'].forEach(bot => {
    lines.push(`User-agent: ${bot}`, aiRule);
  });

  return lines.join('\n') + '\n';
}

function buildLlmTxt(cfg: SiteConfig): string {
  const base = cfg.siteUrl.replace(/\/$/, '');
  const lines = [
    `# LLM.txt — ${cfg.siteTitle}`,
    '# Инструкции для AI-агентов и языковых моделей',
    '',
    '## О сайте',
    `Name: ${cfg.siteTitle}`,
    `URL: ${base || cfg.siteUrl}`,
  ];
  if (cfg.siteAuthor)      lines.push(`Author: ${cfg.siteAuthor}`);
  if (cfg.siteDescription) lines.push(`Description: ${cfg.siteDescription}`);
  const policyMap: Record<string, string> = {
    'allowed':                  'allowed',
    'allowed-with-attribution': 'allowed-with-attribution',
    'disallowed':               'disallowed',
  };
  lines.push(
    '',
    '## Политика использования',
    `AI-Training: ${policyMap[cfg.llmUsagePolicy] ?? 'allowed'}`,
    `AI-Indexing: ${cfg.llmEnabled ? 'allowed' : 'disallowed'}`,
  );
  if (cfg.llmContact)     lines.push('', '## Контакт', `Contact: ${cfg.llmContact}`);
  if (cfg.llmDescription) lines.push('', '## Описание контента', cfg.llmDescription);
  if (base)               lines.push('', '## Карта сайта', `Sitemap: ${base}/sitemap.xml`);
  return lines.join('\n') + '\n';
}

// ─── Parsers ──────────────────────────────────────────────────────────────────

function parseSeoTs(content: string): Partial<SiteConfig> {
  const result: Record<string, string> = {};
  // Парсим строки вида:   key: "value",
  const re = /^\s*(\w+):\s*["']([^"'\n]*)["'],?\s*$/gm;
  let m: RegExpExecArray | null;
  while ((m = re.exec(content)) !== null) {
    result[m[1]] = m[2];
  }
  return result as Partial<SiteConfig>;
}

function parseRobotsTxt(content: string): Pick<SiteConfig, 'robotsAllowAll' | 'robotsDisallowPaths' | 'llmEnabled'> {
  const lines = content.split('\n').map(l => l.trim());

  // Находим блок User-agent: *
  let inMainBlock = false;
  const disallowPaths: string[] = [];

  for (const line of lines) {
    if (line === 'User-agent: *') { inMainBlock = true; continue; }
    // Новый User-agent блок — заканчиваем парсинг основного
    if (line.startsWith('User-agent:') && line !== 'User-agent: *') { inMainBlock = false; continue; }
    if (inMainBlock && line.startsWith('Disallow:')) {
      const p = line.replace('Disallow:', '').trim();
      if (p && p !== '/') disallowPaths.push(p);
    }
  }

  // AI crawlers: ищем GPTBot блок
  const gptIdx = lines.findIndex(l => l === 'User-agent: GPTBot');
  let llmEnabled = true;
  if (gptIdx !== -1) {
    for (let i = gptIdx + 1; i < lines.length; i++) {
      if (lines[i].startsWith('User-agent:')) break;
      if (lines[i].startsWith('Allow:'))    { llmEnabled = true;  break; }
      if (lines[i].startsWith('Disallow:')) { llmEnabled = false; break; }
    }
  }

  return {
    robotsAllowAll:      disallowPaths.length === 0,
    robotsDisallowPaths: disallowPaths.join('\n'),
    llmEnabled,
  };
}

function parseLlmTxt(content: string): Pick<SiteConfig, 'llmUsagePolicy' | 'llmContact' | 'llmDescription'> {
  const result: Pick<SiteConfig, 'llmUsagePolicy' | 'llmContact' | 'llmDescription'> = {
    llmUsagePolicy: 'allowed',
    llmContact:     '',
    llmDescription: '',
  };

  const lines = content.split('\n');
  let inDesc = false;
  const descLines: string[] = [];

  for (const line of lines) {
    if (line.startsWith('AI-Training:')) {
      const v = line.replace('AI-Training:', '').trim();
      if (v === 'disallowed' || v === 'allowed-with-attribution' || v === 'allowed') {
        result.llmUsagePolicy = v;
      }
    }
    if (line.startsWith('Contact:')) {
      result.llmContact = line.replace('Contact:', '').trim();
    }
    if (line === '## Описание контента') { inDesc = true; continue; }
    if (inDesc && line.startsWith('##')) { inDesc = false; }
    if (inDesc && line.trim()) descLines.push(line);
  }

  if (descLines.length) result.llmDescription = descLines.join('\n');
  return result;
}

// ─── UI helpers ───────────────────────────────────────────────────────────────

function useInpStyle(t: TTokens): React.CSSProperties {
  return {
    width: '100%', padding: '6px 8px', borderRadius: 6,
    border: `1px solid ${t.inpBorder}`, background: t.inpBg,
    color: t.fg, fontSize: 11, outline: 'none', fontFamily: t.mono,
    boxSizing: 'border-box' as const,
  };
}

interface FieldProps { label: string; hint?: string; wide?: boolean; t: TTokens; children: React.ReactNode; }
function Field({ label, hint, wide, t, children }: FieldProps) {
  return (
    <div style={{ gridColumn: wide ? '1 / -1' : 'auto' }}>
      <div style={{
        fontSize: 9, fontWeight: 700, color: t.fgSub,
        textTransform: 'uppercase' as const, letterSpacing: '0.07em', marginBottom: 4,
      }}>
        {label}
        {hint && <span style={{ fontWeight: 400, textTransform: 'none' as const, letterSpacing: 0, marginLeft: 5, opacity: 0.65 }}>{hint}</span>}
      </div>
      {children}
    </div>
  );
}

interface SelProps { value: string; onChange: (v: string) => void; options: { value: string; label: string }[]; t: TTokens; }
function Sel({ value, onChange, options, t }: SelProps) {
  const s = useInpStyle(t);
  return (
    <select value={value} onChange={e => onChange(e.target.value)} style={{ ...s, cursor: 'pointer' }}>
      {options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
    </select>
  );
}

interface ToggleProps { value: boolean; onChange: (v: boolean) => void; label: string; t: TTokens; }
function Toggle({ value, onChange, label, t }: ToggleProps) {
  return (
    <button onClick={() => onChange(!value)} style={{
      display: 'flex', alignItems: 'center', gap: 8,
      background: 'none', border: 'none', cursor: 'pointer',
      color: value ? t.fg : t.fgMuted, fontSize: 11,
      padding: '2px 0', fontFamily: t.mono, textAlign: 'left' as const,
    }}>
      <div style={{
        width: 32, height: 18, borderRadius: 9,
        position: 'relative' as const, flexShrink: 0,
        background: value ? t.success : t.border,
        transition: 'background 0.2s',
      }}>
        <div style={{
          position: 'absolute' as const, top: 2,
          left: value ? 14 : 2,
          width: 14, height: 14, borderRadius: '50%',
          background: '#fff', transition: 'left 0.2s',
        }} />
      </div>
      {label}
    </button>
  );
}

interface SectionProps {
  icon: React.ReactNode; title: string; badge?: string;
  defaultOpen?: boolean; t: TTokens; children: React.ReactNode;
}
function Section({ icon, title, badge, defaultOpen = true, t, children }: SectionProps) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{ borderBottom: `1px solid ${t.border}` }}>
      <button onClick={() => setOpen(v => !v)} style={{
        width: '100%', display: 'flex', alignItems: 'center', gap: 7,
        padding: '9px 12px', border: 'none', background: t.surface,
        color: t.fgMuted, cursor: 'pointer', textAlign: 'left' as const,
        fontSize: 10, fontWeight: 700, fontFamily: t.mono,
        textTransform: 'uppercase' as const, letterSpacing: '0.08em',
      }}>
        {open ? <ChevronDown size={10}/> : <ChevronRight size={10}/>}
        <span style={{ color: t.fgSub, display: 'flex', alignItems: 'center' }}>{icon}</span>
        <span style={{ flex: 1 }}>{title}</span>
        {badge && (
          <span style={{
            fontSize: 9, padding: '1px 6px', borderRadius: 4,
            background: t.accentSoft, color: t.fgMuted,
            border: `1px solid ${t.border}`,
          }}>{badge}</span>
        )}
      </button>
      {open && (
        <div style={{ padding: '8px 12px 12px', display: 'flex', flexDirection: 'column' as const, gap: 8 }}>
          {children}
        </div>
      )}
    </div>
  );
}

function Preview({ content, t }: { content: string; t: TTokens }) {
  return (
    <div>
      <div style={{
        fontSize: 9, color: t.fgSub, marginBottom: 4,
        textTransform: 'uppercase' as const, letterSpacing: '0.07em',
      }}>Превью</div>
      <pre style={{
        fontSize: 10, color: t.fgMuted, background: t.inpBg,
        border: `1px solid ${t.border}`, borderRadius: 6,
        padding: '6px 8px', margin: 0, fontFamily: t.mono,
        whiteSpace: 'pre-wrap' as const, maxHeight: 180, overflowY: 'auto',
      }}>{content}</pre>
    </div>
  );
}

// ─── SitePanel ────────────────────────────────────────────────────────────────

export default function SitePanel() {
  const t = useContext(ThemeTokensContext);
  const [cfg, setCfg]         = useState<SiteConfig>({ ...DEFAULTS });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving]   = useState(false);
  const [saved,  setSaved]    = useState(false);
  const [dirty,  setDirty]    = useState(false);
  const cfgRef = useRef(cfg);
  useEffect(() => { cfgRef.current = cfg; }, [cfg]);

  const inp = useInpStyle(t);

  const set = (key: keyof SiteConfig) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
      setCfg(p => ({ ...p, [key]: e.target.value }));
      setDirty(true);
    };

  const setVal = (key: keyof SiteConfig, val: string | boolean) => {
    setCfg(p => ({ ...p, [key]: val }));
    setDirty(true);
  };

  // ─── Load ────────────────────────────────────────────────────────────────

  const load = useCallback(async () => {
    setLoading(true);
    try {
      let merged: SiteConfig = { ...DEFAULTS };

      // 1. seo.ts
      const { content: seoContent } = await bridge.readFile(SEO_PATH);
      if (seoContent.trim()) {
        const parsed = parseSeoTs(seoContent);
        merged = { ...merged, ...parsed };
      }

      // 2. robots.txt — всегда читаем и парсим заново
      const { content: robotsContent } = await bridge.readFile(ROBOTS_PATH);
      if (robotsContent.trim()) {
        const robotsParsed = parseRobotsTxt(robotsContent);
        merged = { ...merged, ...robotsParsed };
      }

      // 3. llm.txt
      const { content: llmContent } = await bridge.readFile(LLM_PATH);
      if (llmContent.trim()) {
        const llmParsed = parseLlmTxt(llmContent);
        merged = { ...merged, ...llmParsed };
      }

      setCfg(merged);
    } catch (e: any) {
      toast.error('Ошибка загрузки: ' + e.message);
    } finally {
      setDirty(false);
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  // ─── Save ────────────────────────────────────────────────────────────────

  const save = useCallback(async () => {
    setSaving(true);
    try {
      const c = cfgRef.current;
      await bridge.writeFile(SEO_PATH,    buildSeoTs(c));
      await bridge.writeFile(ROBOTS_PATH, buildRobotsTxt(c));
      await bridge.writeFile(LLM_PATH,    buildLlmTxt(c));
      setDirty(false);
      setSaved(true);
      setTimeout(() => setSaved(false), 2500);
      toast.success('Сохранено: seo.ts · robots.txt · llm.txt');
    } catch (e: any) {
      toast.error(e.message);
    } finally {
      setSaving(false);
    }
  }, []);

  useEffect(() => {
    const h = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); save(); }
    };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, [save]);

  if (loading) return (
    <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, color: t.fgMuted }}>
      <Loader2 size={16} style={{ animation: 'devSpinAnim 1s linear infinite' }}/>
      <span style={{ fontSize: 12 }}>Загрузка...</span>
    </div>
  );

  const domainBadge = cfg.siteUrl
    ? cfg.siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, '')
    : 'домен не задан';

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

      {/* Top bar */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: 8, padding: '7px 10px',
        borderBottom: `1px solid ${t.border}`, background: t.surface, flexShrink: 0,
      }}>
        <div style={{
          fontSize: 11, color: t.fgMuted, fontFamily: t.mono,
          padding: '3px 8px', borderRadius: 6,
          background: t.accentSoft, border: `1px solid ${t.border}`,
          overflow: 'hidden', textOverflow: 'ellipsis',
          whiteSpace: 'nowrap' as const, maxWidth: 160,
        }}>
          {domainBadge}
        </div>
        <span style={{ flex: 1, fontSize: 10, color: t.fgSub, fontFamily: t.mono }}>
          {dirty && <span style={{ color: t.warning, marginRight: 4 }}>●</span>}
          seo.ts · robots.txt · llm.txt
        </span>
        <button onClick={load} style={{
          display: 'flex', alignItems: 'center', gap: 4, padding: '5px 9px',
          borderRadius: 6, border: `1px solid ${t.border}`,
          background: 'transparent', color: t.fgMuted,
          cursor: 'pointer', fontSize: 11, fontFamily: t.mono,
        }}
          onMouseEnter={e => (e.currentTarget.style.background = t.surfaceHov)}
          onMouseLeave={e => (e.currentTarget.style.background = 'transparent')}
        >
          <RefreshCw size={10}/> Обновить
        </button>
        <button onClick={save} disabled={saving} style={{
          display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px',
          borderRadius: 6,
          border: `1px solid ${saved ? t.success + '66' : dirty ? t.borderStrong : t.border}`,
          background: saved ? 'rgba(34,197,94,0.1)' : dirty ? t.surfaceHov : 'transparent',
          color: saved ? t.success : dirty ? t.fg : t.fgMuted,
          cursor: 'pointer', fontSize: 11, fontFamily: t.mono, fontWeight: dirty ? 500 : 400,
        }}>
          {saving && <Loader2 size={10} style={{ animation: 'devSpinAnim 1s linear infinite' }}/>}
          {saved ? <><Check size={10}/> Сохранено</> : 'Сохранить'}
          {!saved && !saving && (
            <span style={{
              fontSize: 9, color: t.fgSub, background: t.inpBg,
              border: `1px solid ${t.border}`, borderRadius: 3, padding: '1px 4px',
            }}>Ctrl+S</span>
          )}
        </button>
      </div>

      {/* Scrollable content */}
      <div style={{ flex: 1, overflowY: 'auto' }} className="adm-scroll">

        {/* ── Основное ── */}
        <Section icon={<Globe size={10}/>} title="Основное" t={t}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>

            <Field label="Домен / URL сайта" hint="https://example.com" wide t={t}>
              <input value={cfg.siteUrl} onChange={set('siteUrl')}
                placeholder="https://hub.opensophy.com" style={inp}/>
            </Field>

            <Field label="Название сайта" wide t={t}>
              <input value={cfg.siteTitle} onChange={set('siteTitle')}
                placeholder="Hub — Opensophy" style={inp}/>
            </Field>

            <Field label="Описание" hint="до 160 символов" wide t={t}>
              <textarea value={cfg.siteDescription} onChange={set('siteDescription')}
                placeholder="Краткое описание сайта..." rows={3}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}/>
              <div style={{
                fontSize: 9, marginTop: 2,
                color: cfg.siteDescription.length > 160 ? t.danger : t.fgSub,
              }}>
                {cfg.siteDescription.length} / 160
              </div>
            </Field>

            <Field label="Ключевые слова" hint="через запятую" wide t={t}>
              <input value={cfg.keywords} onChange={set('keywords')}
                placeholder="opensophy, hub, AI" style={inp}/>
            </Field>

            <Field label="Автор" t={t}>
              <input value={cfg.siteAuthor} onChange={set('siteAuthor')}
                placeholder="Opensophy" style={inp}/>
            </Field>

            <Field label="Язык" t={t}>
              <Sel value={cfg.siteLang} onChange={v => setVal('siteLang', v)} t={t} options={[
                { value: 'ru', label: 'ru — Русский' },
                { value: 'en', label: 'en — English' },
                { value: 'de', label: 'de — Deutsch' },
                { value: 'fr', label: 'fr — Français' },
                { value: 'es', label: 'es — Español' },
                { value: 'zh', label: 'zh — 中文' },
              ]}/>
            </Field>

          </div>
        </Section>

        {/* ── SEO мета-теги ── */}
        <Section icon={<Search size={10}/>} title="SEO и мета-теги" t={t} defaultOpen={false}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>

            <Field label="Meta Robots" wide t={t}>
              <Sel value={cfg.metaRobots} onChange={v => setVal('metaRobots', v)} t={t} options={[
                { value: 'index, follow',     label: '✅ index, follow (по умолчанию)' },
                { value: 'noindex, follow',   label: '🚫 noindex, follow' },
                { value: 'index, nofollow',   label: 'index, nofollow' },
                { value: 'noindex, nofollow', label: '🚫 noindex, nofollow' },
              ]}/>
            </Field>

            <Field label="OG Image" hint="путь к картинке" wide t={t}>
              <input value={cfg.ogImage} onChange={set('ogImage')}
                placeholder="/og-image.png" style={inp}/>
            </Field>

            <Field label="OG Type" t={t}>
              <Sel value={cfg.ogType} onChange={v => setVal('ogType', v)} t={t} options={[
                { value: 'website', label: 'website' },
                { value: 'article', label: 'article' },
              ]}/>
            </Field>

            <Field label="OG Locale" t={t}>
              <input value={cfg.ogLocale} onChange={set('ogLocale')}
                placeholder="ru_RU" style={inp}/>
            </Field>

            <Field label="Twitter Card" t={t}>
              <Sel value={cfg.twitterCard} onChange={v => setVal('twitterCard', v)} t={t} options={[
                { value: 'summary_large_image', label: 'summary_large_image' },
                { value: 'summary',             label: 'summary' },
              ]}/>
            </Field>

            <Field label="Twitter @site" t={t}>
              <input value={cfg.twitterSite} onChange={set('twitterSite')}
                placeholder="@opensophy" style={inp}/>
            </Field>

          </div>
        </Section>

        {/* ── Robots.txt ── */}
        <Section icon={<Globe size={10}/>} title="Robots.txt" badge="public/robots.txt" t={t} defaultOpen={false}>
          <Toggle
            value={cfg.robotsAllowAll}
            onChange={v => setVal('robotsAllowAll', v)}
            label="Разрешить индексирование всего сайта"
            t={t}
          />
          {!cfg.robotsAllowAll && (
            <Field label="Запрещённые пути (каждый на новой строке)" wide t={t}>
              <textarea value={cfg.robotsDisallowPaths} onChange={set('robotsDisallowPaths')}
                placeholder={'/api/\n/*.json$\n/private/'}
                rows={4}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}/>
            </Field>
          )}
          <Preview content={buildRobotsTxt(cfg)} t={t}/>
        </Section>

        {/* ── LLM.txt ── */}
        <Section icon={<Bot size={10}/>} title="LLM.txt / AI-боты" badge="public/llm.txt" t={t} defaultOpen={false}>
          <Toggle
            value={cfg.llmEnabled}
            onChange={v => setVal('llmEnabled', v)}
            label="Разрешить AI-ботам (GPT, Claude, Perplexity) индексировать сайт"
            t={t}
          />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
            <Field label="Политика обучения AI" wide t={t}>
              <Sel value={cfg.llmUsagePolicy} onChange={v => setVal('llmUsagePolicy', v)} t={t} options={[
                { value: 'allowed',                   label: '✅ Разрешено для обучения' },
                { value: 'allowed-with-attribution',  label: '📝 Разрешено с указанием источника' },
                { value: 'disallowed',                label: '🚫 Запрещено для обучения' },
              ]}/>
            </Field>
            <Field label="Контакт" hint="email или URL" wide t={t}>
              <input value={cfg.llmContact} onChange={set('llmContact')}
                placeholder="contact@example.com" style={inp}/>
            </Field>
            <Field label="Описание контента для AI" wide t={t}>
              <textarea value={cfg.llmDescription} onChange={set('llmDescription')}
                placeholder="Документация по AI и кибербезопасности..." rows={3}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}/>
            </Field>
          </div>
          <Preview content={buildLlmTxt(cfg)} t={t}/>
        </Section>

        <div style={{ height: 24 }}/>
      </div>
    </div>
  );
}