/**
 * SitePanel v2 — рабочая SEO-панель
 *
 * Хранит всё в одном файле: src/shared/data/seo.ts
 * Также пишет: public/robots.txt, public/llm.txt
 *
 * При загрузке читает src/shared/data/seo.ts через bridge.readFile,
 * парсит значения и показывает их в полях.
 */

import React, { useState, useEffect, useCallback, useContext, useRef } from 'react';
import { bridge } from '../useDevBridge';
import { toast } from '../components/Toast';
import { ThemeTokensContext } from '../DevPanel';
import type { TTokens } from '../DevPanel';
import {
  Globe, Search, Bot, RefreshCw,
  Loader2, ChevronDown, ChevronRight, AlertTriangle, Check,
} from 'lucide-react';

// ─── Types ────────────────────────────────────────────────────────────────────

interface SiteConfig {
  // Основное
  siteTitle: string;
  siteDescription: string;
  siteUrl: string;
  siteLang: string;
  siteAuthor: string;
  // SEO
  metaRobots: string;
  googleVerify: string;
  yandexVerify: string;
  // OG
  ogImage: string;
  ogType: string;
  ogLocale: string;
  // Twitter
  twitterCard: string;
  twitterSite: string;
  // Robots.txt
  robotsAllowAll: boolean;
  robotsDisallowPaths: string;
  // LLM.txt / GEO
  llmEnabled: boolean;
  llmDescription: string;
  llmUsagePolicy: string;
  llmContact: string;
  // Дополнительно
  keywords: string;
}

const EMPTY: SiteConfig = {
  siteTitle: '',
  siteDescription: '',
  siteUrl: '',
  siteLang: 'ru',
  siteAuthor: '',
  metaRobots: 'index, follow',
  googleVerify: '',
  yandexVerify: '',
  ogImage: '/og-image.png',
  ogType: 'website',
  ogLocale: 'ru_RU',
  twitterCard: 'summary_large_image',
  twitterSite: '',
  robotsAllowAll: true,
  robotsDisallowPaths: '',
  llmEnabled: true,
  llmDescription: '',
  llmUsagePolicy: 'allowed',
  llmContact: '',
  keywords: '',
};

// ─── File paths ───────────────────────────────────────────────────────────────

const SEO_PATH    = 'src/shared/data/seo.ts';
const ROBOTS_PATH = 'public/robots.txt';
const LLM_PATH    = 'public/llm.txt';

// ─── Serializers ──────────────────────────────────────────────────────────────

function serializeSeoTs(cfg: SiteConfig): string {
  return `// Auto-generated by Hub Dev Panel — do not edit manually
// To update: open Dev Panel → Сайт tab

export const SEO_CONFIG = {
  siteTitle:           ${JSON.stringify(cfg.siteTitle)},
  siteDescription:     ${JSON.stringify(cfg.siteDescription)},
  siteUrl:             ${JSON.stringify(cfg.siteUrl)},
  siteLang:            ${JSON.stringify(cfg.siteLang)},
  siteAuthor:          ${JSON.stringify(cfg.siteAuthor)},
  metaRobots:          ${JSON.stringify(cfg.metaRobots)},
  googleVerify:        ${JSON.stringify(cfg.googleVerify)},
  yandexVerify:        ${JSON.stringify(cfg.yandexVerify)},
  ogImage:             ${JSON.stringify(cfg.ogImage)},
  ogType:              ${JSON.stringify(cfg.ogType)},
  ogLocale:            ${JSON.stringify(cfg.ogLocale)},
  twitterCard:         ${JSON.stringify(cfg.twitterCard)},
  twitterSite:         ${JSON.stringify(cfg.twitterSite)},
  keywords:            ${JSON.stringify(cfg.keywords)},
} as const;
`;
}

function serializeRobots(cfg: SiteConfig): string {
  const lines: string[] = ['User-agent: *'];

  if (cfg.robotsAllowAll) {
    lines.push('Allow: /');
  } else {
    const disallowed = cfg.robotsDisallowPaths
      .split('\n')
      .map(l => l.trim())
      .filter(Boolean);
    if (disallowed.length === 0) {
      lines.push('Allow: /');
    } else {
      lines.push('Allow: /');
      disallowed.forEach(p => lines.push(`Disallow: ${p}`));
    }
  }

  if (cfg.siteUrl) {
    const base = cfg.siteUrl.replace(/\/$/, '');
    lines.push('');
    lines.push(`Sitemap: ${base}/sitemap.xml`);
    lines.push(`Sitemap: ${base}/sitemap-index.xml`);
  }

  // AI crawlers
  lines.push('');
  lines.push('# AI crawlers');
  if (cfg.llmEnabled) {
    lines.push('User-agent: GPTBot');
    lines.push('Allow: /');
    lines.push('User-agent: Claude-Web');
    lines.push('Allow: /');
    lines.push('User-agent: anthropic-ai');
    lines.push('Allow: /');
    lines.push('User-agent: PerplexityBot');
    lines.push('Allow: /');
  } else {
    lines.push('User-agent: GPTBot');
    lines.push('Disallow: /');
    lines.push('User-agent: Claude-Web');
    lines.push('Disallow: /');
    lines.push('User-agent: anthropic-ai');
    lines.push('Disallow: /');
    lines.push('User-agent: PerplexityBot');
    lines.push('Disallow: /');
  }

  return lines.join('\n') + '\n';
}

function serializeLlm(cfg: SiteConfig): string {
  const base = cfg.siteUrl.replace(/\/$/, '');
  const lines: string[] = [
    `# ${cfg.siteTitle || 'Site'} — LLM.txt`,
    `# ${cfg.siteDescription || ''}`,
    '',
    '## About',
    `Name: ${cfg.siteTitle}`,
    `URL: ${base || cfg.siteUrl}`,
    cfg.siteAuthor ? `Author: ${cfg.siteAuthor}` : '',
    cfg.siteDescription ? `Description: ${cfg.siteDescription}` : '',
    '',
    '## Usage Policy',
    `AI-Training: ${cfg.llmUsagePolicy === 'allowed' ? 'allowed' : cfg.llmUsagePolicy === 'disallowed' ? 'disallowed' : 'allowed-with-attribution'}`,
    `AI-Indexing: ${cfg.llmEnabled ? 'allowed' : 'disallowed'}`,
    '',
  ];

  if (cfg.llmDescription) {
    lines.push('## Content Description');
    lines.push(cfg.llmDescription);
    lines.push('');
  }

  if (cfg.llmContact) {
    lines.push('## Contact');
    lines.push(`Contact: ${cfg.llmContact}`);
    lines.push('');
  }

  if (base) {
    lines.push('## Sitemaps');
    lines.push(`Sitemap: ${base}/sitemap.xml`);
    lines.push('');
  }

  return lines.filter(l => l !== null).join('\n');
}

// ─── Parser ───────────────────────────────────────────────────────────────────

function parseSeoTs(content: string): Partial<SiteConfig> {
  const result: Partial<SiteConfig> = {};
  // Extract string values: key: "value",
  const strRe = /(\w+):\s*["']([^"']*?)["'],?/g;
  let m: RegExpExecArray | null;
  while ((m = strRe.exec(content)) !== null) {
    const key = m[1] as keyof SiteConfig;
    if (key in EMPTY) {
      (result as Record<string, string>)[key] = m[2];
    }
  }
  return result;
}

function parseRobotsTxt(content: string): Partial<SiteConfig> {
  const result: Partial<SiteConfig> = {};
  const hasDisallow = content.includes('Disallow: /\n') || content.match(/^Disallow:\s+\/\s*$/m);
  const allowLine = content.match(/^Allow:\s+\/\s*$/m);
  // If there's a Disallow: / for main user-agent block
  const lines = content.split('\n');
  let inMainBlock = false;
  let disallowPaths: string[] = [];
  for (const line of lines) {
    if (line.trim() === 'User-agent: *') { inMainBlock = true; continue; }
    if (line.trim().startsWith('User-agent:') && line.trim() !== 'User-agent: *') { inMainBlock = false; continue; }
    if (inMainBlock && line.trim().startsWith('Disallow:')) {
      const path = line.replace('Disallow:', '').trim();
      if (path && path !== '/') disallowPaths.push(path);
    }
  }
  result.robotsAllowAll = disallowPaths.length === 0;
  result.robotsDisallowPaths = disallowPaths.join('\n');

  // AI crawlers
  const gpbotBlock = content.match(/User-agent:\s*GPTBot[\s\S]*?(?:Allow|Disallow):\s*(\S+)/);
  if (gpbotBlock) {
    result.llmEnabled = gpbotBlock[1] === '/';
  }

  return result;
}

// ─── Section component ────────────────────────────────────────────────────────

interface SectionProps {
  icon: React.ReactNode;
  title: string;
  badge?: string;
  defaultOpen?: boolean;
  t: TTokens;
  children: React.ReactNode;
}

function Section({ icon, title, badge, defaultOpen = true, t, children }: SectionProps) {
  const [open, setOpen] = useState(defaultOpen);
  return (
    <div style={{ borderBottom: `1px solid ${t.border}` }}>
      <button
        onClick={() => setOpen(v => !v)}
        style={{
          width: '100%', display: 'flex', alignItems: 'center', gap: 7,
          padding: '9px 12px', border: 'none', background: t.surface,
          color: t.fgMuted, cursor: 'pointer', textAlign: 'left' as const,
          fontSize: 10, fontWeight: 700, fontFamily: t.mono,
          textTransform: 'uppercase' as const, letterSpacing: '0.08em',
        }}
      >
        {open ? <ChevronDown size={10} /> : <ChevronRight size={10} />}
        <span style={{ color: t.fgSub, display: 'flex' }}>{icon}</span>
        <span style={{ flex: 1 }}>{title}</span>
        {badge && (
          <span style={{
            fontSize: 9, padding: '1px 6px', borderRadius: 4,
            background: t.accentSoft, color: t.fgMuted,
            border: `1px solid ${t.border}`, marginLeft: 4,
          }}>
            {badge}
          </span>
        )}
      </button>
      {open && (
        <div style={{ padding: '8px 12px 12px', display: 'flex', flexDirection: 'column' as const, gap: 8 }}>
          {children}
        </div>
      )}
    </div>
  );
}

// ─── Field component ──────────────────────────────────────────────────────────

interface FieldProps {
  label: string;
  hint?: string;
  t: TTokens;
  children: React.ReactNode;
  wide?: boolean;
}

function Field({ label, hint, t, children, wide }: FieldProps) {
  return (
    <div style={{ gridColumn: wide ? '1 / -1' : 'auto' }}>
      <div style={{ fontSize: 9, fontWeight: 700, color: t.fgSub, textTransform: 'uppercase' as const, letterSpacing: '0.07em', marginBottom: 4 }}>
        {label}
        {hint && <span style={{ fontWeight: 400, textTransform: 'none' as const, letterSpacing: 0, marginLeft: 6, color: t.fgSub, opacity: 0.7 }}>{hint}</span>}
      </div>
      {children}
    </div>
  );
}

// ─── Input helpers ────────────────────────────────────────────────────────────

function useInpStyle(t: TTokens): React.CSSProperties {
  return {
    width: '100%', padding: '6px 8px', borderRadius: 6,
    border: `1px solid ${t.inpBorder}`, background: t.inpBg,
    color: t.fg, fontSize: 11, outline: 'none', fontFamily: t.mono,
    boxSizing: 'border-box' as const,
  };
}

interface SelectProps {
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
  t: TTokens;
}

function Sel({ value, onChange, options, t }: SelectProps) {
  const inp = useInpStyle(t);
  return (
    <select
      value={value}
      onChange={e => onChange(e.target.value)}
      style={{ ...inp, cursor: 'pointer', appearance: 'none' as const }}
    >
      {options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
    </select>
  );
}

// ─── Toggle ───────────────────────────────────────────────────────────────────

interface ToggleProps {
  value: boolean;
  onChange: (v: boolean) => void;
  label: string;
  t: TTokens;
}

function Toggle({ value, onChange, label, t }: ToggleProps) {
  return (
    <button
      onClick={() => onChange(!value)}
      style={{
        display: 'flex', alignItems: 'center', gap: 8,
        background: 'none', border: 'none', cursor: 'pointer',
        color: value ? t.fg : t.fgMuted, fontSize: 11,
        padding: '2px 0', fontFamily: t.mono, textAlign: 'left' as const,
      }}
    >
      <div style={{
        width: 32, height: 18, borderRadius: 9,
        background: value ? t.success : t.border,
        position: 'relative' as const, flexShrink: 0,
        transition: 'background 0.2s',
      }}>
        <div style={{
          position: 'absolute' as const, top: 2,
          left: value ? 14 : 2,
          width: 14, height: 14, borderRadius: '50%',
          background: '#fff',
          transition: 'left 0.2s',
        }} />
      </div>
      {label}
    </button>
  );
}

// ─── SitePanel ────────────────────────────────────────────────────────────────

export default function SitePanel() {
  const t = useContext(ThemeTokensContext);
  const [cfg, setCfg]         = useState<SiteConfig>({ ...EMPTY });
  const [loading, setLoading] = useState(true);
  const [saving, setSaving]   = useState(false);
  const [saved, setSaved]     = useState(false);
  const [dirty, setDirty]     = useState(false);
  const cfgRef = useRef(cfg);
  useEffect(() => { cfgRef.current = cfg; }, [cfg]);

  const inp = useInpStyle(t);

  // Helper to update a field
  const set = (key: keyof SiteConfig) => (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    setCfg(p => ({ ...p, [key]: e.target.value }));
    setDirty(true);
  };
  const setVal = (key: keyof SiteConfig, val: string | boolean) => {
    setCfg(p => ({ ...p, [key]: val }));
    setDirty(true);
  };

  // ─── Load ────────────────────────────────────────────────────────────────

  const load = useCallback(async () => {
    setLoading(true);
    let merged: SiteConfig = { ...EMPTY };

    // 1. Try to read seo.ts
    try {
      const { content } = await bridge.readFile(SEO_PATH);
      const parsed = parseSeoTs(content);
      merged = { ...merged, ...parsed };
    } catch {
      // file doesn't exist yet — use defaults
    }

    // 2. Also read robots.txt for toggle state
    try {
      const { content } = await bridge.readFile(ROBOTS_PATH);
      const robotsParsed = parseRobotsTxt(content);
      merged = { ...merged, ...robotsParsed };
    } catch {
      // ignore
    }

    setCfg(merged);
    setDirty(false);
    setLoading(false);
  }, []);

  useEffect(() => { load(); }, [load]);

  // ─── Save ────────────────────────────────────────────────────────────────

  const save = useCallback(async () => {
    setSaving(true);
    try {
      const c = cfgRef.current;

      // 1. seo.ts — main source of truth
      await bridge.writeFile(SEO_PATH, serializeSeoTs(c));

      // 2. robots.txt
      await bridge.writeFile(ROBOTS_PATH, serializeRobots(c));

      // 3. llm.txt
      await bridge.writeFile(LLM_PATH, serializeLlm(c));

      setDirty(false);
      setSaved(true);
      setTimeout(() => setSaved(false), 2500);
      toast.success('SEO настройки сохранены (seo.ts, robots.txt, llm.txt)');
    } catch (e: unknown) {
      toast.error('Ошибка: ' + (e as Error).message);
    } finally {
      setSaving(false);
    }
  }, []);

  // Ctrl+S
  useEffect(() => {
    const h = (e: KeyboardEvent) => {
      if ((e.ctrlKey || e.metaKey) && e.key === 's') { e.preventDefault(); save(); }
    };
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, [save]);

  if (loading) return (
    <div style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, color: t.fgMuted }}>
      <Loader2 size={16} style={{ animation: 'devSpinAnim 1s linear infinite' }} />
      <span style={{ fontSize: 12 }}>Загрузка...</span>
    </div>
  );

  const domainDisplay = cfg.siteUrl
    ? cfg.siteUrl.replace(/^https?:\/\//, '').replace(/\/$/, '')
    : '—';

  return (
    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

      {/* Top bar */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: 8, padding: '7px 10px',
        borderBottom: `1px solid ${t.border}`, background: t.surface, flexShrink: 0,
      }}>
        {/* Domain badge */}
        <div style={{
          fontSize: 11, color: t.fgMuted, fontFamily: t.mono,
          padding: '3px 8px', borderRadius: 6,
          background: t.accentSoft, border: `1px solid ${t.border}`,
          overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const,
          maxWidth: 160, flexShrink: 1,
        }}>
          {domainDisplay}
        </div>

        <span style={{ flex: 1, fontSize: 10, color: t.fgSub, fontFamily: t.mono }}>
          {dirty && <span style={{ color: t.warning, marginRight: 4 }}>●</span>}
          seo.ts · robots.txt · llm.txt
        </span>

        <button onClick={load} style={{
          display: 'flex', alignItems: 'center', gap: 4, padding: '5px 9px',
          borderRadius: 6, border: `1px solid ${t.border}`, background: 'transparent',
          color: t.fgMuted, cursor: 'pointer', fontSize: 11, fontFamily: t.mono,
        }}>
          <RefreshCw size={10} /> Обновить
        </button>

        <button onClick={save} disabled={saving} style={{
          display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px',
          borderRadius: 6,
          border: `1px solid ${saved ? t.success + '66' : dirty ? t.borderStrong : t.border}`,
          background: saved
            ? (t.bg === '#111112' ? 'rgba(34,197,94,0.1)' : 'rgba(22,163,74,0.08)')
            : dirty ? t.surfaceHov : 'transparent',
          color: saved ? t.success : dirty ? t.fg : t.fgMuted,
          cursor: 'pointer', fontSize: 11, fontFamily: t.mono, fontWeight: dirty ? 500 : 400,
        }}>
          {saving && <Loader2 size={10} style={{ animation: 'devSpinAnim 1s linear infinite' }} />}
          {saved ? <><Check size={10} /> Сохранено</> : 'Сохранить'}
          {!saved && !saving && (
            <span style={{ fontSize: 9, color: t.fgSub, background: t.inpBg, border: `1px solid ${t.border}`, borderRadius: 3, padding: '1px 4px' }}>
              Ctrl+S
            </span>
          )}
        </button>
      </div>

      {/* Scrollable content */}
      <div style={{ flex: 1, overflowY: 'auto' }} className="adm-scroll">

        {/* ── Основное ── */}
        <Section icon={<Globe size={10} />} title="Основное" t={t}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>

            <Field label="Домен / URL" hint="https://example.com" t={t} wide>
              <input
                value={cfg.siteUrl}
                onChange={set('siteUrl')}
                placeholder="https://hub.opensophy.com"
                style={inp}
              />
            </Field>

            <Field label="Название сайта" t={t} wide>
              <input
                value={cfg.siteTitle}
                onChange={set('siteTitle')}
                placeholder="Hub — Opensophy"
                style={inp}
              />
            </Field>

            <Field label="Описание" hint="до 160 символов" t={t} wide>
              <textarea
                value={cfg.siteDescription}
                onChange={set('siteDescription')}
                placeholder="Краткое описание сайта..."
                rows={3}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}
              />
              <div style={{ fontSize: 9, color: cfg.siteDescription.length > 160 ? t.danger : t.fgSub, marginTop: 3 }}>
                {cfg.siteDescription.length} / 160
              </div>
            </Field>

            <Field label="Ключевые слова" hint="через запятую" t={t} wide>
              <input
                value={cfg.keywords}
                onChange={set('keywords')}
                placeholder="opensophy, hub, документация, AI"
                style={inp}
              />
            </Field>

            <Field label="Автор" t={t}>
              <input
                value={cfg.siteAuthor}
                onChange={set('siteAuthor')}
                placeholder="Opensophy"
                style={inp}
              />
            </Field>

            <Field label="Язык" t={t}>
              <Sel
                value={cfg.siteLang}
                onChange={v => setVal('siteLang', v)}
                t={t}
                options={[
                  { value: 'ru', label: 'ru — Русский' },
                  { value: 'en', label: 'en — English' },
                  { value: 'de', label: 'de — Deutsch' },
                  { value: 'fr', label: 'fr — Français' },
                  { value: 'zh', label: 'zh — 中文' },
                ]}
              />
            </Field>

          </div>
        </Section>

        {/* ── SEO / Индексирование ── */}
        <Section icon={<Search size={10} />} title="SEO / Индексирование" t={t}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>

            <Field label="Meta Robots" t={t} wide>
              <Sel
                value={cfg.metaRobots}
                onChange={v => setVal('metaRobots', v)}
                t={t}
                options={[
                  { value: 'index, follow',    label: '✅ index, follow (по умолчанию)' },
                  { value: 'noindex, follow',  label: '🚫 noindex, follow' },
                  { value: 'index, nofollow',  label: '⚠️ index, nofollow' },
                  { value: 'noindex, nofollow', label: '🚫 noindex, nofollow (скрыть всё)' },
                ]}
              />
            </Field>

            <Field label="Open Graph тип" t={t}>
              <Sel
                value={cfg.ogType}
                onChange={v => setVal('ogType', v)}
                t={t}
                options={[
                  { value: 'website', label: 'website' },
                  { value: 'article', label: 'article' },
                  { value: 'blog',    label: 'blog' },
                ]}
              />
            </Field>

            <Field label="OG Locale" t={t}>
              <input value={cfg.ogLocale} onChange={set('ogLocale')} placeholder="ru_RU" style={inp} />
            </Field>

            <Field label="OG Image" hint="/path/to/image.png" t={t} wide>
              <input value={cfg.ogImage} onChange={set('ogImage')} placeholder="/og-image.png" style={inp} />
            </Field>

            <Field label="Twitter Card" t={t}>
              <Sel
                value={cfg.twitterCard}
                onChange={v => setVal('twitterCard', v)}
                t={t}
                options={[
                  { value: 'summary_large_image', label: 'summary_large_image' },
                  { value: 'summary',             label: 'summary' },
                ]}
              />
            </Field>

            <Field label="Twitter @site" t={t}>
              <input value={cfg.twitterSite} onChange={set('twitterSite')} placeholder="@opensophy" style={inp} />
            </Field>

            <Field label="Google Verify" hint="content= из Search Console" t={t} wide>
              <input value={cfg.googleVerify} onChange={set('googleVerify')} placeholder="abc123..." style={inp} />
            </Field>

            <Field label="Yandex Verify" t={t} wide>
              <input value={cfg.yandexVerify} onChange={set('yandexVerify')} placeholder="abc123..." style={inp} />
            </Field>

          </div>
        </Section>

        {/* ── Robots.txt ── */}
        <Section icon={<Globe size={10} />} title="Robots.txt" badge="public/robots.txt" t={t}>
          <Toggle
            value={cfg.robotsAllowAll}
            onChange={v => setVal('robotsAllowAll', v)}
            label="Разрешить индексирование всего сайта"
            t={t}
          />

          {!cfg.robotsAllowAll && (
            <Field label="Запрещённые пути (каждый на новой строке)" t={t} wide>
              <textarea
                value={cfg.robotsDisallowPaths}
                onChange={set('robotsDisallowPaths')}
                placeholder={'/admin\n/private\n/api'}
                rows={4}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}
              />
            </Field>
          )}

          {/* Preview */}
          <div>
            <div style={{ fontSize: 9, color: t.fgSub, marginBottom: 4, textTransform: 'uppercase' as const, letterSpacing: '0.07em' }}>
              Превью robots.txt
            </div>
            <pre style={{
              fontSize: 10, color: t.fgMuted, background: t.inpBg,
              border: `1px solid ${t.border}`, borderRadius: 6,
              padding: '6px 8px', margin: 0, fontFamily: t.mono,
              whiteSpace: 'pre-wrap' as const, maxHeight: 140, overflowY: 'auto',
            }}>
              {serializeRobots(cfg)}
            </pre>
          </div>
        </Section>

        {/* ── LLM.txt / AI ── */}
        <Section icon={<Bot size={10} />} title="LLM.txt / AI индексирование" badge="public/llm.txt" t={t} defaultOpen={false}>

          <div style={{
            padding: '6px 8px', borderRadius: 6, background: t.inpBg,
            border: `1px solid ${t.border}`, marginBottom: 4,
            display: 'flex', gap: 6, alignItems: 'flex-start',
          }}>
            <AlertTriangle size={11} style={{ color: t.warning, flexShrink: 0, marginTop: 1 }} />
            <span style={{ fontSize: 10, color: t.fgMuted, lineHeight: 1.5 }}>
              LLM.txt — стандарт для управления тем, как AI-боты (ChatGPT, Claude, Perplexity) видят и используют ваш сайт.
            </span>
          </div>

          <Toggle
            value={cfg.llmEnabled}
            onChange={v => setVal('llmEnabled', v)}
            label="Разрешить AI-ботам индексировать сайт"
            t={t}
          />

          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>

            <Field label="Политика обучения AI" t={t} wide>
              <Sel
                value={cfg.llmUsagePolicy}
                onChange={v => setVal('llmUsagePolicy', v)}
                t={t}
                options={[
                  { value: 'allowed',                   label: '✅ Разрешено' },
                  { value: 'allowed-with-attribution',  label: '📝 Разрешено с указанием источника' },
                  { value: 'disallowed',                label: '🚫 Запрещено' },
                ]}
              />
            </Field>

            <Field label="Контакт" hint="email или URL" t={t} wide>
              <input
                value={cfg.llmContact}
                onChange={set('llmContact')}
                placeholder="contact@example.com"
                style={inp}
              />
            </Field>

            <Field label="Описание контента для AI" t={t} wide>
              <textarea
                value={cfg.llmDescription}
                onChange={set('llmDescription')}
                placeholder="Этот сайт содержит документацию по AI и кибербезопасности..."
                rows={3}
                style={{ ...inp, resize: 'vertical' as const, lineHeight: 1.5 }}
              />
            </Field>

          </div>

          {/* Preview */}
          <div>
            <div style={{ fontSize: 9, color: t.fgSub, marginBottom: 4, textTransform: 'uppercase' as const, letterSpacing: '0.07em' }}>
              Превью llm.txt
            </div>
            <pre style={{
              fontSize: 10, color: t.fgMuted, background: t.inpBg,
              border: `1px solid ${t.border}`, borderRadius: 6,
              padding: '6px 8px', margin: 0, fontFamily: t.mono,
              whiteSpace: 'pre-wrap' as const, maxHeight: 160, overflowY: 'auto',
            }}>
              {serializeLlm(cfg)}
            </pre>
          </div>

        </Section>

        {/* Bottom padding */}
        <div style={{ height: 24 }} />
      </div>
    </div>
  );
}