sonar.projectKey=opensophy-projects_hub
sonar.organization=opensophy-projects

sonar.sources=src,scripts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=.test-build/**,dist/**
