// Auto-generated by Hub Dev Panel — Вкладка "Сайт"
// Редактировать через Dev Panel, не вручную

export const SEO_CONFIG = {
  siteTitle:       "Hub — Opensophy",
  siteDescription: "Hub проекта Opensophy — центр знаний по ИИ и кибербезопасности.",
  siteUrl:         "https://hub.opensophy.com",
  siteLang:        "ru",
  siteAuthor:      "Opensophy",
  keywords:        "opensophy, hub, документация, AI, кибербезопасность",
  metaRobots:      "index, follow",
  ogImage:         "/og-image.png",
  ogType:          "website",
  ogLocale:        "ru_RU",
  twitterCard:     "summary_large_image",
  twitterSite:     "",
} as const;