/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

// biome-ignore lint/suspicious/noExplicitAny: Auto-generated registry index with dynamic component types
export const Index: Record<string, any> = {
  "chart": {
    name: "chart",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/shared/evilcharts/ui/chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/shared/evilcharts/ui/tooltip.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/tooltip.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/tooltip.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "legend": {
    name: "legend",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/shared/evilcharts/ui/legend.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/legend.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/legend.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "dot": {
    name: "dot",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/shared/evilcharts/ui/dot.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/dot.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/dot.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "evil-brush": {
    name: "evil-brush",
    description: "",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart"],
    files: [{
      path: "@/shared/evilcharts/ui/evil-brush.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/evil-brush.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/evil-brush.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "background": {
    name: "background",
    description: "",
    type: "registry:component",
    registryDependencies: undefined,
    files: [{
      path: "@/shared/evilcharts/ui/background.tsx",
      type: "registry:component",
      target: "components/evilcharts/ui/background.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/ui/background.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "area-chart": {
    name: "area-chart",
    description: "Area chart component",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/dot","@evilcharts/evil-brush","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/area-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/area-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "line-chart": {
    name: "line-chart",
    description: "Line chart component",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/dot","@evilcharts/evil-brush","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/line-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/line-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "bar-chart": {
    name: "bar-chart",
    description: "Bar chart component",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/evil-brush","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/bar-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "composed-chart": {
    name: "composed-chart",
    description: "Composed chart component combining bar and line charts",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/dot","@evilcharts/evil-brush","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/composed-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/composed-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "pie-chart": {
    name: "pie-chart",
    description: "Pie chart component with donut, gradient, and glow effects",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/pie-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/pie-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radial-chart": {
    name: "radial-chart",
    description: "Radial bar chart component with full and semi-circle variants",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/radial-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/radial-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "radar-chart": {
    name: "radar-chart",
    description: "Radar chart component with filled and lines variants",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/legend","@evilcharts/dot","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/radar-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/radar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "sankey-chart": {
    name: "sankey-chart",
    description: "Sankey chart component for visualizing flow data with nodes and links",
    type: "registry:component",
    registryDependencies: ["@evilcharts/chart","@evilcharts/tooltip","@evilcharts/background"],
    files: [{
      path: "@/shared/evilcharts/charts/sankey-chart.tsx",
      type: "registry:component",
      target: "components/evilcharts/charts/sankey-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/charts/sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-area-chart": {
    name: "ex-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-area-chart": {
    name: "ex-gradient-colors-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-bump-area-chart": {
    name: "ex-gradient-colors-bump-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-bump-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-bump-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-area-chart": {
    name: "ex-loading-state-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-default-type-area-chart": {
    name: "ex-default-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-default-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-default-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stacked-type-area-chart": {
    name: "ex-stacked-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-stacked-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-stacked-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-expanded-type-area-chart": {
    name: "ex-expanded-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-expanded-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-expanded-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bump-curve-type-area-chart": {
    name: "ex-bump-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bump-curve-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bump-curve-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-step-curve-type-area-chart": {
    name: "ex-step-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-step-curve-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-step-curve-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-monotoney-curve-type-area-chart": {
    name: "ex-monotoney-curve-type-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-monotoney-curve-type-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-monotoney-curve-type-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-solid-stroke-area-chart": {
    name: "ex-solid-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-solid-stroke-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-solid-stroke-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-dashed-stroke-area-chart": {
    name: "ex-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-dashed-stroke-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-dashed-stroke-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-animated-dashed-stroke-area-chart": {
    name: "ex-animated-dashed-stroke-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-animated-dashed-stroke-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-animated-dashed-stroke-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-area-variant-area-chart": {
    name: "ex-gradient-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-reverse-area-variant-area-chart": {
    name: "ex-gradient-reverse-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-reverse-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-reverse-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-solid-area-variant-area-chart": {
    name: "ex-solid-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-solid-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-solid-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-dotted-area-variant-area-chart": {
    name: "ex-dotted-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-dotted-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-dotted-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-lines-area-variant-area-chart": {
    name: "ex-lines-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-lines-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-lines-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hatched-area-variant-area-chart": {
    name: "ex-hatched-area-variant-area-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/area-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-hatched-area-variant-area-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-hatched-area-variant-area-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-line-chart": {
    name: "ex-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-line-chart": {
    name: "ex-gradient-colors-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-bump-line-chart": {
    name: "ex-gradient-colors-bump-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-bump-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-bump-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-line-chart": {
    name: "ex-loading-state-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bump-curve-type-line-chart": {
    name: "ex-bump-curve-type-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bump-curve-type-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bump-curve-type-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-step-curve-type-line-chart": {
    name: "ex-step-curve-type-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-step-curve-type-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-step-curve-type-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-monotoney-curve-type-line-chart": {
    name: "ex-monotoney-curve-type-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-monotoney-curve-type-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-monotoney-curve-type-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-solid-stroke-line-chart": {
    name: "ex-solid-stroke-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-solid-stroke-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-solid-stroke-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-dashed-stroke-line-chart": {
    name: "ex-dashed-stroke-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-dashed-stroke-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-dashed-stroke-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-animated-dashed-stroke-line-chart": {
    name: "ex-animated-dashed-stroke-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-animated-dashed-stroke-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-animated-dashed-stroke-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-desktop-line-chart": {
    name: "ex-glowing-desktop-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-desktop-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-desktop-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-mobile-line-chart": {
    name: "ex-glowing-mobile-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-mobile-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-mobile-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-buffer-line-chart": {
    name: "ex-buffer-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-buffer-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-buffer-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-dots-line-chart": {
    name: "ex-bg-dots-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-dots-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-dots-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-grid-line-chart": {
    name: "ex-bg-grid-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-grid-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-grid-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-cross-hatch-line-chart": {
    name: "ex-bg-cross-hatch-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-cross-hatch-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-cross-hatch-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-diagonal-lines-line-chart": {
    name: "ex-bg-diagonal-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-diagonal-lines-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-diagonal-lines-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-plus-line-chart": {
    name: "ex-bg-plus-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-plus-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-plus-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-falling-triangles-line-chart": {
    name: "ex-bg-falling-triangles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-falling-triangles-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-falling-triangles-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-4-pointed-star-line-chart": {
    name: "ex-bg-4-pointed-star-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-4-pointed-star-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-4-pointed-star-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-tiny-checkers-line-chart": {
    name: "ex-bg-tiny-checkers-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-tiny-checkers-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-tiny-checkers-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-overlapping-circles-line-chart": {
    name: "ex-bg-overlapping-circles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-overlapping-circles-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-overlapping-circles-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-wiggle-lines-line-chart": {
    name: "ex-bg-wiggle-lines-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-wiggle-lines-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-wiggle-lines-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bg-bubbles-line-chart": {
    name: "ex-bg-bubbles-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bg-bubbles-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bg-bubbles-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-buffer-bar-chart": {
    name: "ex-buffer-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-buffer-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-buffer-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bar-chart": {
    name: "ex-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-bar-chart": {
    name: "ex-gradient-colors-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-bar-chart": {
    name: "ex-loading-state-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-default-variant-bar-chart": {
    name: "ex-default-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-default-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-default-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hatched-variant-bar-chart": {
    name: "ex-hatched-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-hatched-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-hatched-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-duotone-variant-bar-chart": {
    name: "ex-duotone-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-duotone-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-duotone-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-duotone-reverse-variant-bar-chart": {
    name: "ex-duotone-reverse-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-duotone-reverse-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-duotone-reverse-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-variant-bar-chart": {
    name: "ex-gradient-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stripped-variant-bar-chart": {
    name: "ex-stripped-variant-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-stripped-variant-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-stripped-variant-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stacked-type-bar-chart": {
    name: "ex-stacked-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-stacked-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-stacked-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-percent-type-bar-chart": {
    name: "ex-percent-type-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-percent-type-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-percent-type-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-horizontal-layout-bar-chart": {
    name: "ex-horizontal-layout-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-horizontal-layout-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-horizontal-layout-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hover-highlight-bar-chart": {
    name: "ex-hover-highlight-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-hover-highlight-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-hover-highlight-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-desktop-bar-chart": {
    name: "ex-glowing-desktop-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-desktop-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-desktop-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-mobile-bar-chart": {
    name: "ex-glowing-mobile-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-mobile-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-mobile-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-composed-chart": {
    name: "ex-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-composed-chart": {
    name: "ex-gradient-colors-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-composed-chart": {
    name: "ex-loading-state-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hatched-variant-composed-chart": {
    name: "ex-hatched-variant-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-hatched-variant-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-hatched-variant-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-duotone-variant-composed-chart": {
    name: "ex-duotone-variant-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-duotone-variant-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-duotone-variant-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-variant-composed-chart": {
    name: "ex-gradient-variant-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-variant-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-variant-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-stripped-variant-composed-chart": {
    name: "ex-stripped-variant-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-stripped-variant-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-stripped-variant-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-dashed-stroke-composed-chart": {
    name: "ex-dashed-stroke-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-dashed-stroke-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-dashed-stroke-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-animated-dashed-stroke-composed-chart": {
    name: "ex-animated-dashed-stroke-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-animated-dashed-stroke-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-animated-dashed-stroke-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-bump-curve-composed-chart": {
    name: "ex-bump-curve-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-bump-curve-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-bump-curve-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-dots-composed-chart": {
    name: "ex-dots-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-dots-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-dots-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-hover-highlight-composed-chart": {
    name: "ex-hover-highlight-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-hover-highlight-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-hover-highlight-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-composed-chart": {
    name: "ex-glowing-composed-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/composed-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-composed-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-composed-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-pie-chart": {
    name: "ex-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-pie-chart": {
    name: "ex-gradient-colors-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-donut-pie-chart": {
    name: "ex-donut-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-donut-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-donut-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-padded-pie-chart": {
    name: "ex-padded-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-padded-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-padded-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-overlapping-padded-pie-chart": {
    name: "ex-overlapping-padded-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-overlapping-padded-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-overlapping-padded-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-labels-pie-chart": {
    name: "ex-labels-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-labels-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-labels-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-pie-chart": {
    name: "ex-loading-state-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-pie-chart": {
    name: "ex-glowing-pie-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/pie-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-pie-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-pie-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-radial-chart": {
    name: "ex-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radial-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-radial-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-semi-variant-radial-chart": {
    name: "ex-semi-variant-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radial-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-semi-variant-radial-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-semi-variant-radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-radial-chart": {
    name: "ex-gradient-colors-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radial-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-radial-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-radial-chart": {
    name: "ex-loading-state-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radial-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-radial-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-radial-chart": {
    name: "ex-glowing-radial-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radial-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-radial-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-radial-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-radar-chart": {
    name: "ex-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-lines-variant-radar-chart": {
    name: "ex-lines-variant-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-lines-variant-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-lines-variant-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-circle-grid-radar-chart": {
    name: "ex-circle-grid-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-circle-grid-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-circle-grid-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-radar-chart": {
    name: "ex-gradient-colors-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-radar-chart": {
    name: "ex-loading-state-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-radar-chart": {
    name: "ex-glowing-radar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/radar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-radar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-radar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-sankey-chart": {
    name: "ex-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-gradient-colors-sankey-chart": {
    name: "ex-gradient-colors-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-gradient-colors-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-gradient-colors-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-loading-state-sankey-chart": {
    name: "ex-loading-state-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-loading-state-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-loading-state-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-solid-link-variant-sankey-chart": {
    name: "ex-solid-link-variant-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-solid-link-variant-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-solid-link-variant-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-source-link-variant-sankey-chart": {
    name: "ex-source-link-variant-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-source-link-variant-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-source-link-variant-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-glowing-sankey-chart": {
    name: "ex-glowing-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-glowing-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-glowing-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-labeled-nodes-sankey-chart": {
    name: "ex-labeled-nodes-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-labeled-nodes-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-labeled-nodes-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-outside-labels-sankey-chart": {
    name: "ex-outside-labels-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-outside-labels-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-outside-labels-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-solid-labeled-nodes-sankey-chart": {
    name: "ex-solid-labeled-nodes-sankey-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/sankey-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-solid-labeled-nodes-sankey-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-solid-labeled-nodes-sankey-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-tooltip-default-bar-chart": {
    name: "ex-tooltip-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-tooltip-default-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-tooltip-default-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-tooltip-frosted-glass-bar-chart": {
    name: "ex-tooltip-frosted-glass-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-tooltip-frosted-glass-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-tooltip-frosted-glass-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-square-line-chart": {
    name: "ex-legend-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-square-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-square-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-circle-line-chart": {
    name: "ex-legend-circle-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-circle-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-circle-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-circle-outline-line-chart": {
    name: "ex-legend-circle-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-circle-outline-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-circle-outline-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-rounded-square-line-chart": {
    name: "ex-legend-rounded-square-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-rounded-square-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-rounded-square-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-rounded-square-outline-line-chart": {
    name: "ex-legend-rounded-square-outline-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-rounded-square-outline-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-rounded-square-outline-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-vertical-bar-line-chart": {
    name: "ex-legend-vertical-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-vertical-bar-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-vertical-bar-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-legend-horizontal-bar-line-chart": {
    name: "ex-legend-horizontal-bar-line-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/line-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-legend-horizontal-bar-line-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-legend-horizontal-bar-line-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-chart-config-default-bar-chart": {
    name: "ex-chart-config-default-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-chart-config-default-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-chart-config-default-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "ex-chart-config-icons-bar-chart": {
    name: "ex-chart-config-icons-bar-chart",
    description: "",
    type: "registry:block",
    registryDependencies: ["@evilcharts/bar-chart"],
    files: [{
      path: "@/shared/evilcharts/examples/ex-chart-config-icons-bar-chart.tsx",
      type: "registry:block",
      target: ""
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/examples/ex-chart-config-icons-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "monospace-bar-chart": {
    name: "monospace-bar-chart",
    description: "Monospace bar chart component",
    type: "registry:block",
    registryDependencies: ["@evilcharts/chart"],
    files: [{
      path: "@/shared/evilcharts/blocks/b-monospace-bar-chart.tsx",
      type: "registry:block",
      target: "components/evilcharts/blocks/monospace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/blocks/b-monospace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "hover-trace-bar-chart": {
    name: "hover-trace-bar-chart",
    description: "Bar chart with active value line and animated marker",
    type: "registry:block",
    registryDependencies: ["@evilcharts/chart"],
    files: [{
      path: "@/shared/evilcharts/blocks/b-hover-trace-bar-chart.tsx",
      type: "registry:block",
      target: "components/evilcharts/blocks/hover-trace-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/blocks/b-hover-trace-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "grid-bar-chart": {
    name: "grid-bar-chart",
    description: "Bar chart where each bar is composed of stacked 10x10px squares",
    type: "registry:block",
    registryDependencies: ["@evilcharts/chart"],
    files: [{
      path: "@/shared/evilcharts/blocks/b-grid-bar-chart.tsx",
      type: "registry:block",
      target: "components/evilcharts/blocks/grid-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/blocks/b-grid-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  "isometric-bar-chart": {
    name: "isometric-bar-chart",
    description: "Bar chart with isometric 3D-extruded bars and a highlighted max value",
    type: "registry:block",
    registryDependencies: ["@evilcharts/chart"],
    files: [{
      path: "@/shared/evilcharts/blocks/b-isometric-bar-chart.tsx",
      type: "registry:block",
      target: "components/evilcharts/blocks/isometric-bar-chart.tsx"
    }],
    component: React.lazy(async () => {
      const mod = await import("@/shared/evilcharts/blocks/b-isometric-bar-chart.tsx")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    }),
    categories: undefined,
    meta: undefined,
  },
  }